### ISSUE TITLE
Patience diff mixes mine/other and old/new

### ISSUE THREAD

**Issue by jnavila** [janestreet/patience_diff#2]
This mixing does not make it clear which one corresponds to which one. The prototype for get_hunks requests `~mine` and `~other`, but the resulting hunks contain ranges that are using the Old|New| ADTs... with no visible relationships between the types and the parameters.

**Comment by jnavila** [comment]
Digging in the source code:

https://github.com/janestreet/patience_diff/blob/bd30e3d0e259bd388f5b344b7fd6b70d54a74362/src/patience_diff.ml#L218-L221

It turns out `mine` matches `Old`, and `other` matches `New`, for which I had taken the crossed equivalences in my application.

**Comment by bcc32** [comment]
Thanks for the suggestion!  We ended up settling on using the following names consistently for the two diff inputs: `prev` and `next`.  Neither is an OCaml keyword, so they can be used without a trailing `_` as argument and variable names, and they have the same length so the align vertically quite nicely :)
