### ISSUE TITLE
One optional argument among labeled arguments is no longer optional?

### ISSUE THREAD

**Issue by jnavila** [janestreet/patience_diff#3]
https://github.com/janestreet/patience_diff/blob/0e5c44af937829bb96903c8945bb879b0f04dc7c/src/patience_diff.mli#L164-L170

Switching from 0.9.0 to 0.10.0, the new optional argument does not seem to be erasable:

```
Error: This expression has type
         ?big_enough:int ->
         ListPainter.t Patience_diff_lib.Patience_diff.Hunk.t list
       but an expression was expected of type 'a list
```

**Comment by bcc32** [comment]
Thanks for catching this!  I'm going to fix `get_hunks` and `get_matching_blocks` by adding a unit argument.

**Comment by xclerc** [comment]
Fixed by https://github.com/janestreet/patience_diff/commit/53a85f6045af722e5ba023e2852c77f94b8ea0ef.
