### ISSUE TITLE
Proposal: Remove unneeded "Unified" constructor

### ISSUE THREAD

**Issue by vog** [janestreet/patience_diff#4]
The "Unified" constructor of Range.t appears to be unused. It is never produced and only barely handled.

I propose to simplify the interface by removing it.

Note that this proposal has nothing to do with the `unified` function, which should remain untouched.

**Comment by bcc32** [comment]
Hi @vog, `Unified` is produced by the code in https://github.com/janestreet/patdiff, and it is important in the diff-refining code.  This is the code that produces "changed" diff lines with added/removed words.  (As opposed to "added"/"removed" lines).  I agree that it's a bit confusing that the patience_diff library itself doesn't ever construct that variant, but it's a necessary part of the type.
